import Head from 'next/head'
import { useState } from 'react';
import { LazyImage } from '../components/RandomFox'
import type { MouseEventHandler } from 'react';
import { random } from "lodash";

//random function between 1 and 123
// const random = () => Math.floor(Math.random() * 123) + 1;
const myRandom = () => random(1, 122);

//unique id:
const generateId = () => Math.random().toString(36).substr(2,9);





export default function Home() {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = () => {
    const newImageItem: ImageItem = {
      id: generateId(),
      url:`https://randomfox.ca/images/${myRandom()}.jpg`,
    };
    setImages([...images, newImageItem]);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
       <button onClick={addNewFox}>Add new fox</button> 
        {images.map((image, index) => (
          <div key={image.id} className="p-4">
            <LazyImage src={image.url}
              width="320"
              height="auto"
              className="mx-auto rounded-md bg-gray-300"
              onClick={() => {
                console.log("holi!");
              }}     onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }}/>
          </div>
        ))}
        
      </main>
      <footer></footer>
    </>
  )
}
